"""change password_hash field size

Revision ID: b39ed6dea4a2
Revises: f52d992ade12
Create Date: 2024-09-04 14:11:04.464748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b39ed6dea4a2'
down_revision: Union[str, None] = 'f52d992ade12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('editable_html', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('editable_html_id_seq'::regclass)"))
    op.alter_column('editable_html', 'editor_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index('idx_16413_sqlite_autoindex_editable_html_1', table_name='editable_html')
    op.create_unique_constraint(None, 'editable_html', ['editor_name'])
    op.alter_column('roles', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('roles_id_seq'::regclass)"))
    op.alter_column('roles', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('roles', 'index',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('roles', 'permissions',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index('idx_16408_ix_roles_default', table_name='roles')
    op.drop_index('idx_16408_sqlite_autoindex_roles_1', table_name='roles')
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_unique_constraint(None, 'roles', ['name'])
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.alter_column('users', 'first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'role_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('users', 'uid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.drop_index('idx_16418_ix_users_email', table_name='users')
    op.drop_index('idx_16418_ix_users_first_name', table_name='users')
    op.drop_index('idx_16418_ix_users_last_name', table_name='users')
    op.drop_index('idx_16418_ix_users_phone_number', table_name='users')
    op.drop_index('idx_16418_ix_users_uid', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('idx_16418_ix_users_uid', 'users', ['uid'], unique=True)
    op.create_index('idx_16418_ix_users_phone_number', 'users', ['phone_number'], unique=False)
    op.create_index('idx_16418_ix_users_last_name', 'users', ['last_name'], unique=False)
    op.create_index('idx_16418_ix_users_first_name', 'users', ['first_name'], unique=False)
    op.create_index('idx_16418_ix_users_email', 'users', ['email'], unique=True)
    op.alter_column('users', 'uid',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'role_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.String(length=15),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.create_index('idx_16408_sqlite_autoindex_roles_1', 'roles', ['name'], unique=True)
    op.create_index('idx_16408_ix_roles_default', 'roles', ['default'], unique=False)
    op.alter_column('roles', 'permissions',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('roles', 'index',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('roles', 'name',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('roles', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('roles_id_seq'::regclass)"))
    op.drop_constraint(None, 'editable_html', type_='unique')
    op.create_index('idx_16413_sqlite_autoindex_editable_html_1', 'editable_html', ['editor_name'], unique=True)
    op.alter_column('editable_html', 'editor_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('editable_html', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('editable_html_id_seq'::regclass)"))
    # ### end Alembic commands ###
