"""Update Blacklist model

Revision ID: 219aeb6f0226
Revises: 50e3c79ec695
Create Date: 2024-09-03 16:59:58.766049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219aeb6f0226'
down_revision: Union[str, None] = '50e3c79ec695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('url_url_key', 'url', type_='unique')
    op.create_index(op.f('ix_url_category'), 'url', ['category'], unique=False)
    op.create_index(op.f('ix_url_url'), 'url', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_url'), table_name='url')
    op.drop_index(op.f('ix_url_category'), table_name='url')
    op.create_unique_constraint('url_url_key', 'url', ['url'])
    # ### end Alembic commands ###
