"""Update Blacklist model

Revision ID: 50e3c79ec695
Revises: 91a91f3ab1ce
Create Date: 2024-09-03 16:52:20.925136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50e3c79ec695'
down_revision: Union[str, None] = '91a91f3ab1ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('url', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('url', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               nullable=False)
    op.alter_column('url', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('url', 'date_added',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('url', 'reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               nullable=False)
    op.alter_column('url', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               nullable=False)
    op.drop_index('idx_16537_sqlite_autoindex_url_1', table_name='url')
    op.create_index(op.f('ix_url_id'), 'url', ['id'], unique=False)
    op.create_unique_constraint(None, 'url', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'url', type_='unique')
    op.drop_index(op.f('ix_url_id'), table_name='url')
    op.create_index('idx_16537_sqlite_autoindex_url_1', 'url', ['url'], unique=True)
    op.alter_column('url', 'source',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('url', 'reason',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('url', 'date_added',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('url', 'category',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('url', 'url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('url', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
