"""Add new column

Revision ID: 72a0b0c0b8d8
Revises: da9f2d670731
Create Date: 2024-06-23 16:30:49.518857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a0b0c0b8d8'
down_revision: Union[str, None] = 'da9f2d670731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('api_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_urls_api_key'), 'urls', ['api_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_api_key'), table_name='urls')
    op.drop_column('urls', 'api_key')
    # ### end Alembic commands ###
