"""Remove URLExpiry model

Revision ID: 88e31e3e0c24
Revises: a19c62e9ad50
Create Date: 2024-09-03 16:25:17.059298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88e31e3e0c24'
down_revision: Union[str, None] = 'a19c62e9ad50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_16477_ix_url_expiry_key', table_name='url_expiry')
    op.drop_table('url_expiry')
    op.alter_column('scan_records', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('scan_records', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('scan_records', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('scan_records', 'scan_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('scan_records', 'result',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('scan_records', 'submission_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('scan_records', 'scan_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('scan_records', 'sha256',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_scan_records_id'), 'scan_records', ['id'], unique=False)
    op.alter_column('urls', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('urls', 'key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('urls', 'secret_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('urls', 'target_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('urls', 'clicks',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('urls', 'api_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('urls', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('urls', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('urls', 'favicon_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index('idx_16455_ix_urls_api_key', table_name='urls')
    op.drop_index('idx_16455_ix_urls_key', table_name='urls')
    op.drop_index('idx_16455_ix_urls_secret_key', table_name='urls')
    op.drop_index('idx_16455_ix_urls_target_url', table_name='urls')
    op.create_index(op.f('ix_urls_api_key'), 'urls', ['api_key'], unique=False)
    op.create_index(op.f('ix_urls_id'), 'urls', ['id'], unique=False)
    op.create_index(op.f('ix_urls_key'), 'urls', ['key'], unique=True)
    op.create_index(op.f('ix_urls_secret_key'), 'urls', ['secret_key'], unique=True)
    op.create_index(op.f('ix_urls_target_url'), 'urls', ['target_url'], unique=False)
    op.alter_column('urls_to_check', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('urls_to_check', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_urls_to_check_id'), 'urls_to_check', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_to_check_id'), table_name='urls_to_check')
    op.alter_column('urls_to_check', 'url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('urls_to_check', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_urls_target_url'), table_name='urls')
    op.drop_index(op.f('ix_urls_secret_key'), table_name='urls')
    op.drop_index(op.f('ix_urls_key'), table_name='urls')
    op.drop_index(op.f('ix_urls_id'), table_name='urls')
    op.drop_index(op.f('ix_urls_api_key'), table_name='urls')
    op.create_index('idx_16455_ix_urls_target_url', 'urls', ['target_url'], unique=False)
    op.create_index('idx_16455_ix_urls_secret_key', 'urls', ['secret_key'], unique=True)
    op.create_index('idx_16455_ix_urls_key', 'urls', ['key'], unique=True)
    op.create_index('idx_16455_ix_urls_api_key', 'urls', ['api_key'], unique=False)
    op.alter_column('urls', 'favicon_url',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('urls', 'title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('urls', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('urls', 'api_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('urls', 'clicks',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('urls', 'target_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('urls', 'secret_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('urls', 'key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('urls', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_scan_records_id'), table_name='scan_records')
    op.alter_column('scan_records', 'sha256',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('scan_records', 'scan_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('scan_records', 'submission_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('scan_records', 'result',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('scan_records', 'scan_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('scan_records', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('scan_records', 'url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('scan_records', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('url_expiry',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expiry_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['key'], ['urls.key'], name='url_expiry_key_fkey'),
    sa.PrimaryKeyConstraint('id', name='idx_16477_ix_url_expiry_id')
    )
    op.create_index('idx_16477_ix_url_expiry_key', 'url_expiry', ['key'], unique=True)
    # ### end Alembic commands ###
