"""Update API model

Revision ID: 91a91f3ab1ce
Revises: 88e31e3e0c24
Create Date: 2024-09-03 16:50:08.835210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a91f3ab1ce'
down_revision: Union[str, None] = '88e31e3e0c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_key', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('api_key', 'role_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('api_key', 'api_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.drop_index('idx_16516_ix_api_key_api_key', table_name='api_key')
    op.create_index(op.f('ix_api_key_api_key'), 'api_key', ['api_key'], unique=True)
    op.create_index(op.f('ix_api_key_id'), 'api_key', ['id'], unique=False)
    op.alter_column('roles', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('roles', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.drop_index('idx_16511_sqlite_autoindex_roles_1', table_name='roles')
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_unique_constraint(None, 'roles', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.create_index('idx_16511_sqlite_autoindex_roles_1', 'roles', ['name'], unique=True)
    op.alter_column('roles', 'name',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('roles', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_api_key_id'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_api_key'), table_name='api_key')
    op.create_index('idx_16516_ix_api_key_api_key', 'api_key', ['api_key'], unique=True)
    op.alter_column('api_key', 'api_key',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('api_key', 'role_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('api_key', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
