"""Add is_checked column to urls

Revision ID: 92dfdd7b9ff4
Revises: 72a0b0c0b8d8
Create Date: 2024-07-01 15:01:34.475564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92dfdd7b9ff4'
down_revision: Union[str, None] = '72a0b0c0b8d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('is_checked', sa.Boolean(), nullable=True, server_default=sa.sql.expression.false() ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'is_checked')
    # ### end Alembic commands ###
